name: Gestión Materiales

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:      
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build
    - name: Publish
      run: dotnet publish --configuration Release -o "/var/www/gestionmateriales"
    - name: Deploy
      run: systemctl restart kestrel-gestionmateriales
      
   # SSH
   # - name: SSH Deploy
   #   uses: appleboy/ssh-action@master
   #   with:
   #     host: ${{ secrets.SERVER_URL }}
   #     username: ${{ secrets.SSH_USER }}
   #     password: ${{ secrets.SSH_PASSWORD }}
   #     port: ${{ secrets.SSH_PORT }}
   #     script: |           
   #       systemctl restart kestrel-gestionmateriales
          
   # Deploy por FTP
   # - name: FTP Deploy
   #   uses: SamKirkland/FTP-Deploy-Action@2.0.0
   #   env:
   #     FTP_SERVER: ${{ secrets.FTP_URL }}
   #     FTP_USERNAME: ${{ secrets.FTP_USER }}
   #     FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
   #     METHOD: sftp
   #     PORT: 22
   #     LOCAL_DIR: Build
   #     REMOTE_DIR: gestionmateriales
   #     ARGS: --verbose
   # --delete arg will delete files on the server if you've deleted them in git     
