name: Gestión Materiales

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      id: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      id: build
      run: dotnet build
   # - name: Publish
   #   id: publish
   #   run: dotnet publish --configuration Release -o ./Build
   # - name: FTP Deploy
   #   uses: SamKirkland/FTP-Deploy-Action@2.0.0
   #   env:
   #     FTP_SERVER: ${{ secrets.FTP_URL }}
   #     FTP_USERNAME: ${{ secrets.FTP_USER }}
   #     FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
   #     METHOD: sftp
   #     PORT: 22
   #     LOCAL_DIR: Build
   #     REMOTE_DIR: gestionmateriales
   #     ARGS: --verbose
        # --delete arg will delete files on the server if you've deleted them in git     
    - name: SSH Publish & Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_URL }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          git clone https://github.com/et12practicas/gestionmateriales |
          cd gestionmateriales |
          dotnet build |
          dotnet publish -c Release -o "/var/www/gestionmateriales" |
          rm -Rf gestionamateriales

