name: Gestión Materiales

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      id: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      id: build
      run: dotnet build
    - name: Publish
      id: publish
      run: dotnet publish --configuration Release --self-contained false -o ./Build
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: 66.228.61.32
        FTP_USERNAME: jvelazquez
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        METHOD: sftp
        PORT: 22
        LOCAL_DIR: Build
        ARGS: --verbose
        # --delete arg will delete files on the server if you've deleted them in git     
